{% set repositories = [] -%}
{% for repository in values.repositories -%}
  {% set repositories = repositories.concat(['"' ~ repository ~ '"']) -%}
{% endfor -%}
repositories: [${{ repositories }}]

{% if values.environment == "production" -%}
workflow: "${{ values.cloud_provider }}-${{ values.workflow_name }}-prd"
{% elif values.environment == "sandbox" -%}
workflow: "${{ values.cloud_provider }}-${{ values.workflow_name }}-sdx"
{% elif values.environment == "staging" -%}
workflow: "${{ values.cloud_provider }}-${{ values.workflow_name }}-stg"
{%- endif %}


{% if values.extra_envs -%}
envs:
  {% for env in values.extra_envs -%}
  - name: ${{ env.name }}
    value: ${{ env.value }}
  {% endfor -%}
{%- endif %}

{% if values.init_extra_args -%}
{% set args = [] -%}
{% for arg in values.init_extra_args -%}
  {% set args = args.concat(['"' ~ arg ~ '"']) -%}
{% endfor -%}
init_extra_args: [${{ args }}]
{%- endif %}

{% if (values.role_arn != "") and (values.cloud_provider == "aws") -%}
rolearn: ${{ values.role_arn }}
{% elif (values.azure_tenant != "") and (values.cloud_provider == "azure") -%}
azure_tenant: ${{ values.azure_tenant }}
{%- endif %}
