{% set repositories = [] -%}
{% for repository in values.repositories -%}
  {% set repositories = repositories.concat(['"' ~ repository ~ '"']) -%}
{% endfor -%}
repositories: [${{ repositories }}]

workflow: ${{ values.workflow_name }}

{% if values.extra_envs -%}
envs:
  {% for env in values.extra_envs -%}
  - name: ${{ env.name }}
    value: ${{ env.value }}
  {% endfor -%}
{%- endif %}

{% if values.init_extra_args -%}
{% set args = [] -%}
{% for arg in values.init_extra_args -%}
  {% set args = args.concat(['"' ~ arg ~ '"']) -%}
{% endfor -%}
init_extra_args: [${{ args }}]
{%- endif %}

{% if values.role_arn -%}
rolearn: ${{ values.role_arn }}
{% elif values.azure_tenant -%}
azure_tenant: ${{ values.azure_tenant }}
{%- endif %}
