# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: s3-template
  namespace: stone
  title: "[Autosserviço de Infraestrutura] AWS S3 Bucket"
  description: Cria um bucket s3 como autosserviço
  tags:
    - aws
    - infrastructure
    - storage
spec:
  owner: stone-payments/foundation-experience
  type: resource
  parameters:
    - title: Informações de projeto
      required: [bucket_name,account,owner]
      properties:
        bucket_name:
          pattern: '^[a-z0-9](?:[a-z0-9]|(?<=[a-z0-9])[-.](?=[a-z0-9])){1,61}[a-z0-9]$'
          title: Nome do Bucket S3
          type: string
          description: Nome único do bucket a ser deployado na AWS (lembre-se que o nome do bucket é global)
          ui:autofocus: true
        account:
          title: Contexto/Conta
          type: string
          description: Nome do contexto onde o bucket será deployado (por exemplo, o contexto banking-hml equivale à conta homolog em Banking)
          enum:
            - banking-prd
            - banking-hml
            - banking-sdx
            - credit-prd
            - credit-stg
            - payments-finance-prd
            - payments-finance-stg
            - payments-pagarme-prd
            - payments-pagarme-stg
          enumNames:
            - Banking Production (equivalente à production)
            - Banking Homolog (equivalente à homolog)
            - Banking Sandbox (equivalente à sandbox)
            - Credit Production
            - Credit Staging
            - Payment Finance Production
            - Payment Finance Staging
            - Payment Pagarme Production
            - Payment Pagarme Staging
        block_public:
          title: Bloquear acesso público
          type: boolean
          description: "Para bloquear qualquer acesso público ao bucket (default: true)"
          default: true
        server_side_encryption:
          title: Ativar criptografia
          type: boolean
          description: "Criptografia server side (default: true)"
          default: true
        versioning:
          title: Ativar versionamento
          type: boolean
          description: Se o bucket terá versionamento
          default: false
          ui:autofocus: true
        owner:
          title: Time dono da aplicação
          type: string
          description: Time dono da aplicação que usará o repositório
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

  steps:
    - id: fetch-base
      name: Gerando arquivos terraform do bucket S3
      action: fetch:template
      input:
        url: ./template
        targetPath: "./${{ parameters.bucket_name }}"
        values:
          bucket_name: ${{ parameters.bucket_name }}
          server_side_encryption: ${{ parameters.server_side_encryption }}
          versioning: ${{ parameters.versioning }}
          description: "Bucket S3 ${{ parameters.bucket_name }} criado na conta ${{ parameters.account }}."

    - id: fetch-config
      name: Gerando provider e backend
      action: fetch:template
      input:
        url: ../helpers/config-template/
        targetPath: "./${{ parameters.bucket_name }}"
        values:
          account: ${{ parameters.account }}
          aws_state_bucket_name: state-bucket-test
          aws_state_bucket_region: us-east-1
          aws_state_bucket_key: "aws/${{ parameters.account }}/global/s3/${{ parameters.bucket_name }}/terraform.tfstate"
          aws_provider_role_arn: false
          aws_provider_region: us-east-1

    - id: publish
      name: Abrindo Pull Request
      action: publish:github:pull-request
      input:
        description: add ${{ parameters.bucket_name }}
        repoUrl: github.com?owner=sandesvitor-org&repo=infra-mock
        branchName: ${{ parameters.bucket_name }}
        title: "feat: create ${{ parameters.bucket_name }}"
        targetPath: "aws/${{ parameters.account }}/global/s3"

    - id: register
      name: Registrando componente
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Ir para pull request
        url: ${{ steps.publish.output.remoteUrl }}
        icon: github
