---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: mensageria
  namespace: stone
  title: "[POC] Mensageria"
  description: Cria um bucket s3 como autosserviço
  tags:
    - aws
    - infrastructure
    - storage
spec:
  owner: backstage
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Form
      required: [message]
      properties:
        message:
          title: Message
          type: string
          description: ""

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: order
      name: Criar Order
      action: karavela:core:create-order

    - id: mensageria
      name: Criando Recursos de Mensageria - Mock
      action: karavela:core:platform-api
      input:
        orderID: ${{ steps.order.output.orderID }}
        input: |
          {
            "url": "http://mock-external-api:8080/test",
            "payload": {
              "message": ${{ parameters.message }}
            }
          }
