---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: api-mock-platform
  namespace: stone
  title: "API MOCK Platform"
  description: Cria um recurso qualquer
  tags:
    - aws
    - infrastructure
    - storage
spec:
  owner: backstage
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Form
      required: [message]
      properties:
        message:
          title: Message
          type: string
          description: ""
        tags:
          title: Tags
          type: object
          description: Tags do cluster
          properties:
            cost-center:
              title: Centro de Custo
              type: string
              description: Centro de Custo ao qual o cluster pertence
              ui:help: 'Preencha com o centro de custo ao qual o cluster pertence (ex: 820140020 - ENGINEERING PLATFORMS - FOUNDATION PLATFORM - ENGENHARIA)'
              enumNames:
                - 800060020 

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: order
      name: Criar Order
      action: karavela:core:create-order
      input:
        requester: "sandao@sangue.bom"
        expectedStepCount: 1

    - id: mensageria
      name: Criando Recursos de Mensageria - Mock
      action: karavela:core:connector:platform-api
      input:
        orderID: ${{ steps.order.output.orderID }}
        url: "http://localhost:8080/test"
        body:
          message: "${{ parameters.message }}"
          tags: "${{ parameters.tags }}"
