---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: api-mock-platform
  namespace: stone
  title: "API MOCK Platform"
  description: Cria um recurso qualquer
  tags:
    - aws
    - infrastructure
    - storage
spec:
  owner: backstage
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Form
      required: [message]
      properties:
        message:
          title: Message
          type: string
          description: ""
        tags:
          title: Tags
          type: object
          description: Tags do cluster
          properties:
            cost-center:
              title: Centro de Custo
              type: string
              description: Centro de Custo ao qual o cluster pertence
              ui:help: 'Preencha com o centro de custo ao qual o cluster pertence (ex: 820140020 - ENGINEERING PLATFORMS - FOUNDATION PLATFORM - ENGENHARIA)'
              enumNames:
                - 800060020 - CORP IT - ARQUITETURA CORPORATIVA E INTEGRAÇÕES - ENGENHARIA
                - 800040020 - CORP IT - FORNECEDORES E SOLUÇÕES CORPORATIVAS - ENGENHARIA
                - 800070020 - CORP IT - GOVERNANÇA DE TI - ENGENHARIA
                - 800020020 - CORP IT - INFRAESTRUTURA CORPORATIVA - ENGENHARIA
                - 800050020 - CORP IT - SISTEMAS ADMINISTRATIVOS - ENGENHARIA
                - 800030020 - CORP IT - SISTEMAS BACKOFFICE - ENGENHARIA
                - 800010020 - CORP IT - SUPORTE CORPORATIVO - ENGENHARIA
                - 860290036 - CUSTOMER PLATFORMS - CUSTOMER PLATFORMS - CHATBOT - ENGENHARIA
                - 860290035 - CUSTOMER PLATFORMS - CUSTOMER PLATFORMS - CHATBOT - PRODUTO
                - 860290033 - CUSTOMER PLATF"ORMS - CUSTOMER PLATFORMS - CRM - ENGENHARIA
                - 860290034 - CUSTOMER PLATFORMS - CUSTOMER PLATFORMS - CRM - PRODUTO
                - 860290030 - CUSTOMER PLATFORMS - CUSTOMER PLATFORMS - LLMs - OUTROS
                - 860290032 - CUSTOMER PLATFORMS - CUSTOMER PLATFORMS - WEB - ENGENHARIA
                - 860290031 - CUSTOMER PLATFORMS - CUSTOMER PLATFORMS - WEB - PRODUTO
                - 860290010 - CUSTOMER PLATFORMS - CUSTOMER PLATFORMS - PRODUTO
                - 810120320 - DEFENSE AND AUDIT PLATFORMS - RISK MANAGEMENT PLATFORM - ANTI FRAUDE - ENGENHARIA
                - 810120620 - DEFENSE AND AUDIT PLATFORMS - RISK MANAGEMENT PLATFORM - BANKING - ENGENHARIA
                - 810120020 - DEFENSE AND AUDIT PLATFORMS - RISK MANAGEMENT PLATFORM - ENGENHARIA
                - 820130021 - ENGINEERING PLATFORMS - ANALYTICS ENGINEERING - CORE DATA - ENGENHARIA
                - 820160020 - ENGINEERING PLATFORMS - COMMAND CENTER - ENGENHARIA
                - 820130020 - ENGINEERING PLATFORMS - DATA PLATFORM - ENGENHARIA
                - 820140720 - ENGINEERING PLATFORMS - FOUNDATION PLATFORM - RELIABILITY ENGINEERING - ENGENHARIA
                - 820141020 - ENGINEERING PLATFORMS - FOUNDATION PLATFORM - RELIABILITY ENGINEERING CAPITAL PLATFORM - ENGENHARIA
                - 820140820 - ENGINEERING PLATFORMS - FOUNDATION PLATFORM - RELIABILITY ENGINEERING CARD SCHEMES - ENGENHARIA
                - 820140920 - ENGINEERING PLATFORMS - FOUNDATION PLATFORM - RELIABILITY ENGINEERING DATA PLATFORM - ENGENHARIA
                - 820141120 - ENGINEERING PLATFORMS - FOUNDATION PLATFORM - RELIABILITY ENGINEERING PAYMENTS - ENGENHARIA
                - 820140020 - ENGINEERING PLATFORMS - FOUNDATION PLATFORM - ENGENHARIA
                - 820150020 - ENGINEERING PLATFORMS - INFRASTRUCTURE PLATFORM - ENGENHARIA
                - 820141220 - ENGINEERING PLATFORMS - QA - ENGENHARIA
                - 890420072 - FINANCIAL SERVICE - CONTROLLERSHIP - ENGENHARIA
                - 850250010 - FINANCIAL SERVICE - CONTROLLERSHIP - PRODUTO
                - 890420071 - FINANCIAL SERVICE - CORE LEDGER - ENGENHARIA
                - 870350020 - FINANCIAL SERVICE - FINANCIAL SERVICE - ENGENHARIA
                - 870353220 - FINANCIAL SERVICE - TREASURY - ENGENHARIA
                - 850250011 - FINANCIAL SERVICE - TREASURY - PRODUTO
                - 830180010 - INTERACTION PLATFORM - INTERACTION PLATFORM - PRODUTO
                - 830190020 - INTERACTION PLATFORM - UI PLATFORMS - ENGENHARIA
                - 840200020 - LIFECYCLE PLATFORM - ACCOUNTS (AUTH) - ENGENHARIA
                - 840220010 - LIFECYCLE PLATFORM - ACCOUNTS (AUTH) + AFFILIATION - PRODUTO
                - 840230010 - LIFECYCLE PLATFORM - BILLING + PRICING - PRODUTO
                - 840210020 - LIFECYCLE PLATFORM - BILLING + PRICING + AFFILIATION - ENGENHARIA
                - 850240020 - LOCAL FS SCHEMES - CARD SCHEMES - ENGENHARIA
                - 850240060 - LOCAL FS SCHEMES - CARD SCHEMES - OPERAÇÃO
                - 850240010 - LOCAL FS SCHEMES - CARD SCHEMES - PRODUTO
                - 860271810 - OPERATIONS PLATFORM - ATENDIMENTO E SERVIÇO - LOGÍSTICA - PRODUTO
                - 860271710 - OPERATIONS PLATFORM - ATENDIMENTO E SERVIÇO - RC - PRODUTO
                - 860280020 - OPERATIONS PLATFORM - INTERAÇÃO - ENGENHARIA
                - 860261610 - OPERATIONS PLATFORM - MARKETING E VENDAS - MARCOPOLO - PRODUTO
                - 890400070 - OUTROS - GENTE - OUTROS
                - 890410070 - OUTROS - GESTÃO - OUTROS
                - 890430070 - OUTROS - LIDERANÇA - ENGENHARIA
                - 890420070 - OUTROS - LIDERANÇA - OUTROS
                - 890430071 - OUTROS - NOVOS NEGÓCIOS - OUTROS
                - 870302020 - PRODUCT PLATFORMS - BANKING - CARTÃO DE CRÉDITO - ENGENHARIA
                - 870302010 - PRODUCT PLATFORMS - BANKING - CARTÃO DE CRÉDITO - PRODUTO
                - 870301920 - PRODUCT PLATFORMS - BANKING - CORE - ENGENHARIA
                - 870301910 - PRODUCT PLATFORMS - BANKING - CORE - PRODUTO
                - 870302120 - PRODUCT PLATFORMS - BANKING - SEGUROS - ENGENHARIA
                - 870302110 - PRODUCT PLATFORMS - BANKING - SEGUROS - PRODUTO
                - 870332770 - PRODUCT PLATFORMS - CRÉDITO - GOVERNANÇA & GESTÃO & RECUPERAÇÃO - OPERAÇÃO
                - 870322640 - PRODUCT PLATFORMS - CRÉDITO - PROCESSOS - OPERAÇÃO
                - 870322540 - PRODUCT PLATFORMS - CRÉDITO  - NEGÓCIOS
                - 870312230 - PRODUCT PLATFORMS - CRÉDITO APETITE DE CRÉDITO - CONCESSÃO & PORTFOLIO - RISCO
                - 870342920 - PRODUCT PLATFORMS - CRÉDITO TECNOLOGIA - DADOS - ENGENHARIA
                - 870343020 - PRODUCT PLATFORMS - CRÉDITO TECNOLOGIA - PLATAFORMAS COMPARTILHADAS - ENGENHARIA
                - 870343010 - PRODUCT PLATFORMS - CRÉDITO TECNOLOGIA - PLATAFORMAS COMPARTILHADAS - PRODUTO
                - 830171320 - PRODUCT PLATFORMS - HARDWARE - POS - ENGENHARIA
                - 830171220 - PRODUCT PLATFORMS - HARDWARE - TEF - ENGENHARIA
                - 830170020 - PRODUCT PLATFORMS - HARDWARE - ENGENHARIA
                - 830171420 - PRODUCT PLATFORMS - HARDWARE - PRODUTO
                - 890420073 - PRODUCT PLATFORMS - INVESTMENTS - ENGENHARIA
                - 870363320 - PRODUCT PLATFORMS - PAYMENTS - ACEITAÇÃO - ENGENHARIA
                - 870363310 - PRODUCT PLATFORMS - PAYMENTS - ACEITAÇÃO - PRODUTO
                - 870363520 - PRODUCT PLATFORMS - PAYMENTS - FINANCEIRO - ENGENHARIA
                - 870363510 - PRODUCT PLATFORMS - PAYMENTS - FINANCEIRO - PRODUTO
                - 870363620 - PRODUCT PLATFORMS - PAYMENTS - GESTÃO E CONFIGURAÇÃO - ENGENHARIA
                - 870363610 - PRODUCT PLATFORMS - PAYMENTS - GESTÃO E CONFIGURAÇÃO - PRODUTO
                - 870363420 - PRODUCT PLATFORMS - PAYMENTS - PROCESSAMENTO - ENGENHARIA
                - 870363410 - PRODUCT PLATFORMS - PAYMENTS - PROCESSAMENTO - PRODUTO
                - 870360020 - PRODUCT PLATFORMS - PAYMENTS - ENGENHARIA
                - 870360010 - PRODUCT PLATFORMS - PAYMENTS - PRODUTO
                - 880373720 - SEGMENT TEAMS - EMBEDDED FIN - OPERATION - ENGENHARIA
                - 880373710 - SEGMENT TEAMS - EMBEDDED FIN - OPERATION - PRODUTO
                - 880370020 - SEGMENT TEAMS - EMBEDDED FIN - ENGENHARIA
                - 880370010 - SEGMENT TEAMS - EMBEDDED FIN - PRODUTO
                - 880380020 - SEGMENT TEAMS - MICRO - ENGENHARIA
                - 880380010 - SEGMENT TEAMS - MICRO - PRODUTO
                - 880394210 - SEGMENT TEAMS - SMB - DESIGN - PRODUTO
                - 880390031 - SEGMENT TEAMS - SMB - STONE CLUB - ENGENHARIA
                - 880390030 - SEGMENT TEAMS - SMB - STONE CLUB - PRODUTO
                - 880390020 - SEGMENT TEAMS - SMB - ENGENHARIA
                - 880390010 - SEGMENT TEAMS - SMB - PRODUTO
              enum:
                - "800060020"
                - "800040020"
                - "800070020"
                - "800020020"
                - "800050020"
                - "800030020"
                - "800010020"
                - "860290036"
                - "860290035"
                - "860290033"
                - "860290034"
                - "860290030"
                - "860290032"
                - "860290031"
                - "860290010"
                - "810120320"
                - "810120620"
                - "810120020"
                - "820130021"
                - "820160020"
                - "820130020"
                - "820140720"
                - "820141020"
                - "820140820"
                - "820140920"
                - "820141120"
                - "820140020"
                - "820150020"
                - "820141220"
                - "890420072"
                - "850250010"
                - "890420071"
                - "870350020"
                - "870353220"
                - "850250011"
                - "830180010"
                - "830190020"
                - "840200020"
                - "840220010"
                - "840230010"
                - "840210020"
                - "850240020"
                - "850240060"
                - "850240010"
                - "860271810"
                - "860271710"
                - "860280020"
                - "860261610"
                - "890400070"
                - "890410070"
                - "890430070"
                - "890420070"
                - "890430071"
                - "870302020"
                - "870302010"
                - "870301920"
                - "870301910"
                - "870302120"
                - "870302110"
                - "870332770"
                - "870322640"
                - "870322540"
                - "870312230"
                - "870342920"
                - "870343020"
                - "870343010"
                - "830171320"
                - "830171220"
                - "830170020"
                - "830171420"
                - "890420073"
                - "870363320"
                - "870363310"
                - "870363520"
                - "870363510"
                - "870363620"
                - "870363610"
                - "870363420"
                - "870363410"
                - "870360020"
                - "870360010"
                - "880373720"
                - "880373710"
                - "880370020"
                - "880370010"
                - "880380020"
                - "880380010"
                - "880394210"
                - "880390031"
                - "880390030"
                - "880390020"
                - "880390010"

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: order
      name: Criar Order
      action: karavela:core:create-order
      input:
        offer: "nice-demais-mano"
        requester: "sandao@sangue.bom"
        expectedStepCount: 1

    - id: mensageria
      name: Criando Recursos de Mensageria - Mock
      action: karavela:core:connector:platform-api
      input:
        orderId: ${{ steps.order.output.orderId }}
        url: "http://localhost:8080/test"
        apiName: "controlmanager"
        authType: "none"
        body:
          message: "${{ parameters.message }}"
          tags: "${{ parameters.tags }}"
