---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.bucket_name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/source-location: ${{ values.destination.owner }}/${{ values.destination.repo }}/aws/${{ parameters.account }}/global/s3/${{ parameters.bucket_name }}"
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
