---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: create-resourcee
  title: Autoserviço de Infra
  description: Estudo de backstage templates
spec:
  owner: backstage
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Inromações do Recurso
      required: [resourceType, resourceName]
      properties:
        resourceType:
          title: Tipo de recurso
          type: string
          description: "EX: s3"
          ui:autofocus: true
        resourceName:
          title: Nome do recurso
          type: string
          description: "EX: bucket-test"

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: create
      name: Create Resource
      action: custom:resource:create
      input:
        resourceType: ${{ parameters.resourceType }}
        resourceName: ${{ parameters.resourceName }}

  output:
    links:
      - title: Resultado
        url: ${{ steps.create.output.result }}
