account_settings:
  banking-prd:
    role_arn: "arn:aws:iam::662018048003:role/atlantis-roles-banking"
    account_id: "662018048003"
    aws_state_bucket: "tfstates-production-11d428e3"
  banking-hml:
    role_arn: "arn:aws:iam::129817111992:role/atlantis-roles-banking"
    account_id: "129817111992"
    aws_state_bucket: "tfstates-homolog-f4b29095"
