account_settings:
  banking-prd:
    account_id: "662018048003"
  banking-hml:
    account_id: "129817111992"
  banking-sdx:
    account_id: "584077526265"
  credit-prd:
    account_id: ""
  credit-stg:
    account_id: ""
  payments-finance-prd:
    account_id: ""
  payments-finance-stg:
    account_id: ""
  payments-pagarme-prd:
    account_id: ""
  payments-pagarme-stg:
    account_id: ""
