---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}1182
  annotations:
    {% if values.have_gha -%}
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
    {% endif %}
    {% if values.have_azure_devops -%}
    dev.azure.com/project: DevOps
    dev.azure.com/build-definition: homolog-aws-us-east-1-ec2-newrelic-agent-camel
    {% endif %}
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: split-monorepo
spec:
  type: url
  targets:
    - ./account/bucket-teste-atlantis/catalog-info.yaml
    - ./account/bucket-teste-atlantis-2/catalog-info.yaml

 {% if values.block_public -%}

  {% endif %}
