---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: teste
  title: POC - Create Karavela API
  description: xpto
spec:
  owner: backstage
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Form
      required: [app_name]
      properties:
        app_name:
          title: App Name
          type: string
          description: ""
        email:
          title: User Email
          type: string
          description: ""

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetch-base-infra
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template-infra

    - id: infra
      name: Abrindo Pull Request de Infra
      action: publish:github:pull-request
      input:
        description: Add Infra
        repoUrl: github.com?owner=sandesvitor-org&repo=autoservice
        title: "feat: create ${{ parameters.app_name }}"
        targetPath: "infra/${{ parameters.app_name }}"
        branchName: "feat/add-${{ parameters.app_name }}"


    - id: fetch-base-app
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template-app

    - id: app
      name: Abrindo Pull Request de App
      action: publish:github:pull-request
      input:
        description: Add App
        repoUrl: github.com?owner=sandesvitor-org&repo=application
        title: "feat: create ${{ parameters.app_name }}"
        targetPath: "applications/${{ parameters.app_name }}"
        branchName: "feat/add-${{ parameters.app_name }}"


    - id: change
      name: Create change
      action: stone:change:create
      input:
        offer: create-karavela-application
        email: ${{ parameters.email }}"
        pullRequests:
          - url: ${{ steps.infra.output.remoteUrl }}
            target_path: "infra/${{ parameters.app_name }}"
          - url: ${{ steps.app.output.remoteUrl }}
            target_path: "applications/${{ parameters.app_name }}"

  output:
    links:
      - title: "Página de Status da Change ${{ steps.change.output.changeId }}"
        url: ${{ steps.change.output.changeId }}
        icon: backstage
      - title: Ir para pull request de Infra
        url: ${{ steps.infra.output.remoteUrl }}
        icon: github
      - title: Ir para pull request de Aplicação
        url: ${{ steps.app.output.remoteUrl }}
        icon: github
