---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: create-resourcee-s3
  title: Autoserviço de Infra - AWS S3
  description: Estudo de backstage templates
spec:
  owner: backstage
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Inromações do Recurso
      required: [resourceType]
      properties:
        resourceName:
          title: Nome do recurso
          type: string
          description: "EX: bucket-test"

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        targetPath: ecr-template/
        values:
          name: ${{ parameters.name | replace(' ', '-') | replace('_', '-')}}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        description: add ${{ parameters.name }}
        sourcePath: ecr-template/
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        repoUrl: github.com?owner=pagarme&repo=platform-ecr
        branchName: ${{ parameters.name }}
        title: "feat: create ${{ parameters.name }} ECR repository"
        targetPath: applications/ecr/repos.d

  output:
    links:
      - title: Resultado
        url: ${{ steps.create.output.motivacional }}
